server.port=8888
spring.application.name=config-server

# Config Server lit ses configs dans le repo Brain2Build, branche 'configserver'
spring.cloud.config.server.git.uri=https://github.com/ALEXJERDI/Brain2Build.git
spring.cloud.config.server.git.default-label=configserver
spring.cloud.config.server.git.search-paths=.
