spring.application.name=roomservice
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/room_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=false 


eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

