CREATE TABLE ideas
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(150),
    description VARCHAR(1000),
    ai_score    DOUBLE PRECISION,
    status      VARCHAR(255)                            NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by  BIGINT,
    CONSTRAINT pk_ideas PRIMARY KEY (id)
);

CREATE TABLE project_idea
(
    idea_id    BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    CONSTRAINT pk_project_idea PRIMARY KEY (idea_id, project_id)
);

CREATE TABLE projects
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_name VARCHAR(255),
    status       VARCHAR(255),
    start_date   TIMESTAMP WITHOUT TIME ZONE,
    end_date     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_projects PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nom VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE room_members
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_in_room VARCHAR(50),
    is_lead      BOOLEAN,
    joined_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    worker_id    BIGINT                                  NOT NULL,
    room_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_room_members PRIMARY KEY (id)
);

CREATE TABLE rooms
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    room_name   VARCHAR(255),
    max_members INTEGER                                 NOT NULL,
    is_full     BOOLEAN                                 NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    project_id  BIGINT,
    CONSTRAINT pk_rooms PRIMARY KEY (id)
);

CREATE TABLE user_role
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_user_role PRIMARY KEY (role_id, user_id)
);

CREATE TABLE users
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_type       VARCHAR(20)                             NOT NULL,
    email           VARCHAR(255)                            NOT NULL,
    password        VARCHAR(255)                            NOT NULL,
    nom             VARCHAR(50)                             NOT NULL,
    prenom          VARCHAR(50)                             NOT NULL,
    telephone       VARCHAR(255),
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    privilege_level VARCHAR(255)                            NOT NULL,
    department      VARCHAR(255),
    bio             VARCHAR(255),
    idea_count      INTEGER                                 NOT NULL,
    domaine         VARCHAR(255)                            NOT NULL,
    specialite      VARCHAR(255)                            NOT NULL,
    experience      INTEGER                                 NOT NULL,
    portfolio_url   VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_nom UNIQUE (nom);

ALTER TABLE rooms
    ADD CONSTRAINT uc_rooms_project UNIQUE (project_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE ideas
    ADD CONSTRAINT FK_IDEAS_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES users (id);

ALTER TABLE rooms
    ADD CONSTRAINT FK_ROOMS_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (id);

ALTER TABLE room_members
    ADD CONSTRAINT FK_ROOM_MEMBERS_ON_ROOM FOREIGN KEY (room_id) REFERENCES rooms (id);

ALTER TABLE room_members
    ADD CONSTRAINT FK_ROOM_MEMBERS_ON_WORKER FOREIGN KEY (worker_id) REFERENCES users (id);

ALTER TABLE project_idea
    ADD CONSTRAINT fk_proide_on_idea FOREIGN KEY (idea_id) REFERENCES ideas (id);

ALTER TABLE project_idea
    ADD CONSTRAINT fk_proide_on_project FOREIGN KEY (project_id) REFERENCES projects (id);

ALTER TABLE user_role
    ADD CONSTRAINT fk_user_role_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_role
    ADD CONSTRAINT fk_user_role_on_user FOREIGN KEY (user_id) REFERENCES users (id);